spring.kafka.producer.properties.max.block.ms=2000
spring.kafka.producer.properties.request.timeout.ms=2000
spring.kafka.producer.properties.delivery.timeout.ms=3000
spring.kafka.admin.fail-fast=false
spring.kafka.admin.close-timeout=2s
